name: Android NDK Build (Wrapper Variant)


on: [push]

jobs:
  build-android-wrapper:
    runs-on: ubuntu-latest

    strategy:
          matrix:
            build-type: [debugoptimized, release]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Patch anon_file.c for memfd_create
        run: |
          # SDK 30+ has native memfd_create in NDK
          sed -i 's/#if defined(HAVE_MEMFD_CREATE) \&\& !defined __TERMUX__/#if defined(HAVE_MEMFD_CREATE)/' src/util/anon_file.c
          # sed -i '/with_gallium_drisw_kms = false/{n;s/if system_has_kms_drm/if false/;}' meson.build # Disables DRI in WSI
          # sed -i "s/dep_libudev = dependency('libudev', required : false)/dep_libudev = null_dep/g" meson.build

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              build-essential \
              llvm-20-dev \
              libclang-20-dev \
              libclc-20-dev \
              libllvmspirvlib-20-dev \
              libelf-dev \
              spirv-tools \
              bison \
              flex \
              libdrm-dev \
              pkg-config
          python -m pip install --upgrade pip
          pip install mako PyYAML meson ninja packaging

      # - name: Generate Shims
      #   run: |
      #     unzip shims.zip -d ./

      - name: Generate Host Tools
        run: |
          meson setup build-host \
              -Dplatforms=[] \
              -Dgallium-drivers=[] \
              -Dvulkan-drivers=[] \
              -Dtools=panfrost \
              -Dprecomp-compiler=enabled \
              -Dinstall-precomp-compiler=true \
              -Dllvm=enabled \
              -Dmesa-clc=enabled -Dinstall-mesa-clc=true

          ninja -C build-host src/compiler/clc/mesa_clc src/compiler/spirv/vtn_bindgen2 src/panfrost/clc/panfrost_compile

          ln -sf "build-host/src/compiler/clc/mesa_clc" "build-host/src/compiler/clc/mesa-clc"
          ln -sf "build-host/src/compiler/spirv/vtn_bindgen2" "build-host/src/compiler/spirv/vtn-bindgen2"
          echo "$GITHUB_WORKSPACE/build-host/src/compiler/clc" >> $GITHUB_PATH
          echo "$GITHUB_WORKSPACE/build-host/src/compiler/spirv" >> $GITHUB_PATH
          echo "$GITHUB_WORKSPACE/build-host/src/panfrost/clc" >> $GITHUB_PATH

      - name: Configure Meson
        env:
          PKG_CONFIG_LIBDIR: ${{ github.workspace }}/shims
        run: |
          export ANDROID_NDK_HOME="$ANDROID_NDK_LATEST_HOME"
          export MESON_WORKING_DIR="$GITHUB_WORKSPACE"
          envsubst < android.toml > android-cross.txt

          meson setup build --reconfigure \
              --cross-file android-cross.txt \
              -Dbuildtype=${{ matrix.build-type }} \
              -Dplatforms=android,x11 \
              -Dandroid-stub=true \
              -Dandroid-libbacktrace=disabled \
              -Dplatform-sdk-version=30 \
              -Dglx=disabled \
              -Dgbm=disabled \
              -Degl=disabled \
              -Dopengl=false \
              -Dgles1=disabled \
              -Dgles2=disabled \
              -Dglvnd=disabled \
              -Dvalgrind=disabled \
              -Dgallium-drivers= \
              -Dshared-glapi=disabled \
              -Dzstd=disabled \
              -Dmesa-clc=system \
              -Dprecomp-compiler=system \
              -Dvulkan-drivers=panfrost \
              -Dllvm=disabled -Dpanfrost-kmds=kbase,panthor

      - name: Compile Project
        run: |
          meson compile -C build

      - name: Upload Vulkan Wrapper Artifact
        uses: actions/upload-artifact@v4
        with:
          name: libvulkan_wrapper-aarch64-${{ matrix.build-type }}
          path: build/src/panfrost/vulkan/libvulkan_panfrost.so
          if-no-files-found: error
